name: Terraform Security & Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-checkov:
    name: Terraform Validate & Checkov Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (Dev)
        working-directory: env/Dev
        run: terraform init -backend=false

      - name: Terraform Validate (Dev)
        working-directory: env/Dev
        run: terraform validate

      - name: Terraform Init (Prod)
        working-directory: env/Prod
        run: terraform init -backend=false

      - name: Terraform Validate (Prod)
        working-directory: env/Prod
        run: terraform validate

      - name: Run Checkov (IaC Security Scan)
        run: |
          pip install checkov
          checkov -d . --quiet
